name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Unit tests
        run: yarn test

      - name: Build
        run: yarn build

      - name: Release
        if: contains(github.ref, 'refs/heads/main')
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
