name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18, 20]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8.10

      - name: Install dependencies
        run: pnpm install

      - name: Unit tests
        run: pnpm test

      - name: Build
        run: pnpm build
